#print("+"*10)
#nome = input('qual e seu nome ?')
#print('e um prazer em te conhecer {:-^20} '.format(nome))

#h = int(input('digite um numero: '))
#h1 = int(input('digite outro valor: '))
#h2 = h + h1
#h3 = h * h1
#h4 = h / h1
#h5 = h // h1
#h6 = h ** h1
#print('A soma e: {} \nO produto e: {} \nE a divissao e: {}'.format(h2 , h3 , h4),)
#print('A divissao inteira: {} \nE potencia: {:.5f} \n'.format(h5 , h6))


#  \n  para quebra de linha  no print




from random import choice

n1 = str(input('primeiro aluno: '))
n2 = str(input('segundo aluno: '))
n3 = str(input('terceiro aluno: '))
h4 = str(input('quarto aluno'))
lista = [h1,h2,h3,h4]
escolhido = choice(lista)
print('O valuno escolhidofoi {} '.format(escolhido))





